### ISSUE TITLE
suggestion: Full file path in udev configuration

### ISSUE THREAD

**Issue by mh0rst** [luisbocanegra/linux-guide-split-audio-ports#10]
Hi, first of all thank you for compiling the invaluable guide.
I replicated it on a Ubuntu 23.10 system with a Realtek S1220A sound chip (from ASUS ProArt X670E Creator motherboard).

One deviation I had to make from your guide was to specify the full path to the split-ports-profile.conf in the udev configuration, just specifying the file name didn't work - it seems like at least my version of wireplumber (0.4.14-4ubuntu1) does not search in `/etc/alsa-card-profile/mixer/profile-sets` by default:
```
wireplumber[2946]: profile-set '/usr/share/alsa-card-profile/mixer/profile-sets/split-ports-profile.conf' can't be accessed: Datei oder Verzeichnis nicht gefunden
```
With this udev config, everything is recognized and the split ports are working:

```
SUBSYSTEM!="sound", GOTO="pipewire_end"
ACTION!="change", GOTO="pipewire_end"
KERNEL!="card*", GOTO="pipewire_end"

SUBSYSTEMS=="pci", ATTRS{vendor}=="0x1022", ATTRS{device}=="0x15e3", \
ENV{ACP_PROFILE_SET}="/etc/alsa-card-profile/mixer/profile-sets/split-ports-profile.conf"

LABEL="pipewire_end"
```

**Comment by luisbocanegra** [comment]
Hi, sorry for the long wait. Can you try setting it back to just the file name and run
```sh
pactl list sinks | grep -E 'Name|Desc|State|Port|device.profile-set'
```
I want to add a note to the guide but need a way to check if the profile is being used or not. 

In my case without absolute path the profile is applied properly and I see this:
```yaml
State: IDLE
Name: alsa_output.pci-0000_00_1f.3.analog-stereo-headphones
Description: Built-in Audio Headphones
        device.profile-set = "/etc/alsa-card-profile/mixer/profile-sets/split-ports-profile.conf"
Ports:
Active Port: analog-output-headphones
State: SUSPENDED
Name: alsa_output.pci-0000_00_1f.3.analog-stereo-speaker.2
Description: Built-in Audio Speakers
        device.profile-set = "/etc/alsa-card-profile/mixer/profile-sets/split-ports-profile.conf"
Ports:
Active Port: analog-output-speaker-split
```
